/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToast: typeof import('./src/components/common/AppToast.vue')['default']
    RoleCard: typeof import('./src/components/role/RoleCard.vue')['default']
    RoleEditor: typeof import('./src/components/role/RoleEditor.vue')['default']
    RoleplayControlPanel: typeof import('./src/components/ragStory/RoleplayControlPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoryDebugPanel: typeof import('./src/components/ragStory/StoryDebugPanel.vue')['default']
  }
}
